# Generated by Django 3.0.3 on 2020-05-24 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200520_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsection',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
