# Generated by Django 3.0.3 on 2020-05-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postsection_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsection',
            name='command',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='postsection',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
