# Generated by Django 3.0.3 on 2020-05-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200527_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hyperlink',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postsection',
            name='hyperlink',
            field=models.TextField(blank=True),
        ),
    ]
